# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/cxy/opt/UnrealEngine/UE5

TARGETS = \
	CGHSim-Android-DebugGame  \
	CGHSim-Android-Development  \
	CGHSim-Android-Shipping  \
	CGHSim-Linux-DebugGame  \
	CGHSim-Linux-Development  \
	CGHSim-Linux-Shipping  \
	CGHSim-LinuxArm64-DebugGame  \
	CGHSim-LinuxArm64-Development  \
	CGHSim-LinuxArm64-Shipping  \
	CGHSim \
	CGHSimEditor-Linux-DebugGame  \
	CGHSimEditor-Linux-Development  \
	CGHSimEditor \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend CGHSimEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug CGHSimEditor-Linux-Debug


CGHSim-Android-DebugGame:
	 $(BUILD) CGHSim Android DebugGame  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSim-Android-Development:
	 $(BUILD) CGHSim Android Development  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSim-Android-Shipping:
	 $(BUILD) CGHSim Android Shipping  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSim-Linux-DebugGame:
	 $(BUILD) CGHSim Linux DebugGame  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSim-Linux-Development:
	 $(BUILD) CGHSim Linux Development  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSim-Linux-Shipping:
	 $(BUILD) CGHSim Linux Shipping  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSim-LinuxArm64-DebugGame:
	 $(BUILD) CGHSim LinuxArm64 DebugGame  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSim-LinuxArm64-Development:
	 $(BUILD) CGHSim LinuxArm64 Development  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSim-LinuxArm64-Shipping:
	 $(BUILD) CGHSim LinuxArm64 Shipping  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSim: CGHSim-Linux-Development

CGHSimEditor-Linux-DebugGame:
	 $(BUILD) CGHSimEditor Linux DebugGame  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSimEditor-Linux-Development:
	 $(BUILD) CGHSimEditor Linux Development  -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" $(ARGS)

CGHSimEditor: CGHSimEditor-Linux-Development

ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/cxy/Documents/Unreal Projects/CGHSim/CGHSim.uproject" -Game 

.PHONY: $(TARGETS)
